### ISSUE TITLE
Add multi-language output message support

### ISSUE THREAD

**Issue by LiamSho** [Tyrrrz/CliFx#107]
### Details

This framework is awesome. But unfortunately, it can only output messages in English. I want it can print messages in other languages to offer better user experience. So I wonder if the framework can add multi-language support or just make the output messages customizable. Thanks.

**Comment by Tyrrrz** [comment]
To clarify, you mean the error messages and the help text?

**Comment by LiamSho** [comment]
Yes. The help text and error messages.
For example, "you can run `blablabla` to show help in a specific command", I want to print it in other language.
And others like "USAGE", "DESCRIPTION", "OPTIONS", etc.

**Comment by AbdShullah** [comment]
I think instead of allowing users to change those strings, it may be better to use .resx localization to achieve multi-language output. That way help messages would be in different languages depending on the user pc language. 

In addition, something like this should be added to complement multi-language output support.
```cs
[Command(Description = "HelloWorldDescription", ResourceType = typeof(Resources))] // Search for static string property "HelloWorldDescription" in type "Resources" using reflection and get the value
public class HelloWorldCommand : ICommand
```

**Comment by Tyrrrz** [comment]
Marking this as out-of-scope because:
1. the burden of maintaining different translations for every user-facing string in the library will be too high
2. most CLI tools don't provide support for multiple languages
