### ISSUE TITLE
Support version and help commands

### ISSUE THREAD

**Issue by domn1995** [Tyrrrz/CliFx#52]
Many CLI tools have built-in version and help commands. For example:
```
>git version
git version 2.9.2.windows1

>git help
usage: git [...]
...
```

- Are we interested in supporting this in CliFx? 
- Also, if supporting `help` as a builtin command, do we want it only for the root of the app or to all subcommands? I propose all subcommands.
- For the builtin 'version` command, I think it would only make sense to be built in to the root of the app.

**Comment by Tyrrrz** [comment]
No, I want to avoid adding too many ways of doing the same thing, since we already have the help and version options already. When I started the project design, I was debating whether to use the options or the commands for this, but I've settled on the options as it was more common in my experience.
