### ISSUE TITLE
Allow the non scalar parameter to be optional or have default value

### ISSUE THREAD

**Issue by kamran65536** [Tyrrrz/CliFx#99]
Suppose I have an command like this:
```csharp
[Command("run")]
public class RunThis : ICommand
{
    [CommandParameter(0, ...]
     public string[] NonScalarParameters {get;set;}

    public ValueTask Execute(IConsole console)
    {
         if (NonScalarParameters == null)
             console.Output.WriteLine("I set it to something.");
         else
             console.Output.WriteLine("using parameter values...");
}
````
As command parameters are mandatory, currently it is impossible to say:
```bash
util run p1 p2 p3
util run
```
But it is a common usage for such commands to have default value for the last parameter.

I suggest the following change in CommandBinder
```csharp
            //CommandBinder.BindParameters
            if (remainingParameterSchemas.Any() && 
               ((remainingParameterSchemas.Count != 1) || remainingParameterSchemas[0].Property.IsScalar()))
            {
                throw CliFxException.UserError(
                    "Missing parameter(s):" +
                    Environment.NewLine +
                    remainingParameterSchemas
                        .Select(o => o.GetFormattedIdentifier())
                        .JoinToString(" ")
                );
            }
```

**Comment by Tyrrrz** [comment]
Can you show a more concrete example of what you're trying to achieve? Making parameters mandatory was a design decision because they are not as explicit as options. Generally, if you want to make something optional, you should be using options.

**Comment by alirezanet** [comment]
> Can you show a more concrete example/use case
```
Commands:
   husky install [dir] (default: .husky)    Install Husky hooks
```
you asked for an example.

**Comment by Tyrrrz** [comment]
I think optional parameters will play poorly in cases where there are multiple of them. I recommend using options for optional properties instead.

**Comment by alirezanet** [comment]
I suggest to support optional, **just for the last parameter.**  It solves a lot of issues and it is really helpful.

Recently I migrated my custom CLI to clifx. everything is working fine except clifx caused a lot of unnecessary complexity to my CLI. The above install example is one of them. 
```
husky install <SomeOptionalPath>
```
the other one is really annoying: 
before people could just pass custom arguments directly to their scripts:
e.g
```
dotnet husky exec .husky/hello.csx
dotnet husky exec .husky/hello.csx arg1 arg2 arg3
```
now they have to add `--args`,
```
dotnet husky exec .husky/hello.csx --args arg1 arg2 arg3
```
this may not seem a big deal but it is (especially here) because these commands can be preconfigured in a JSON/YAML file. 
``` json
      {
         "command": "dotnet",
         "args": ["husky", "exec", ".husky/csx/commit-lint.csx", "--args", "${args}"]
      },
```
look at the args part ☹️, it is really confusing after I've added `--args`. 

**This clifx limitation is my only regret after migration.** 

In the end in my opinion the last parameter could be optional and it is really useful. 
I think you don't want to add this feature because of possible conflicts with the cmd routing feature that shouldn't be too hard to solve.

Let me know if you want to support this or not please, I need to decide what to do. 
thanks
